### ISSUE TITLE
RGB color help 

### ISSUE THREAD

**Issue by Ibrahim-El-Sayed** [dragonslayer0531/Luminos#1]
public Color(int red, int green, int blue, int alpha)
{
 if ((red & 255) != red || (green & 255) != green || (blue & 255) != blue || (alpha & 255) != alpha)
throw new IllegalArgumentException("Bad RGB values");

value = (alpha << 24) | (red << 16) | (green << 8) | blue;
falpha = 1;
cs = null;
}

easier function

**Comment by nickclark2016** [comment]
Added it to the experimental branch.  Case closed?
